---

- name: Setting variables in config file php-fpm
  lineinfile: 
    dest: /etc/php-fpm.d/www.conf 
    state: present 
    regexp: "^ *;? *({{ item.key }} *=) *(.*)"
    line: "\\1 {{item.value}}"
    backrefs: yes
  with_dict: "{{ php_fpm_parameters }}"
  notify: restart php-fpm

- name: Put default /etc/php-fpm.conf
  template: 
    src: php-fpm.conf.j2
    dest: "{{ php_conf_dir }}/"
    mode: 0644
  when: "{{ php_fpm_source_tag is defined }}"

- name: Put default php.ini
  template: 
    src: php.ini.j2 
    dest: "{{ php_conf_dir }}/php.ini"
    mode: 0644
    validate: "grep ANSIBLE_MANAGED %s"

- name: Setting variables in config file php.ini
  lineinfile: 
    dest: "{{ php_conf_dir }}/php.ini"
    state: present 
    regexp: "^ *;? *({{ item.key }} *=) *(.*)"
    line: "\\1 {{item.value}}"
    backrefs: yes
  with_dict: "{{ php_parameters }}"
  notify: restart php-fpm
 
